openapi: 3.0.3
info:
  version: 1.0.0
  title: Template
  license:
    name: MIT
servers:
- url: http://#uri/api/template/1.0.0
paths:
  /v1/template:
    get:
      summary: Template me
      operationId: templateGet
      tags:
      - template
      responses:
        200:
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateAdapterModel"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
    post:
      summary: Create a template
      operationId: templatePost
      tags:
      - template
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateAdapterModel"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /v1/template/security:
    get:
      security:
      - oAuth2Password: [read]
      summary: Template me
      operationId: templateGetSecurity
      tags:
      - template
      responses:
        200:
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateAdapterModel"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /v1/template/error:
    get:
      summary: Template me with error
      operationId: templateError
      tags:
      - template
      responses:
        200:
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
components:
  securitySchemes:
    oAuth2Password:
      type: oauth2
      description: See https://developers.getbase.com/docs/rest/articles/oauth2/requests
      flows:
        password:
          tokenUrl: https://api.getbase.com/oauth2/token
          scopes:
            read: Grant read-only access to all your data except for the account and user info
            write: Grant write-only access to all your data except for the account and user info
            profile: Grant read-only access to the account and user info only
  schemas:
    TemplateAdapterModel:
      required:
      - identifier
      - name
      properties:
        identifier:
          type: integer
          format: int32
        name:
          type: string
    ApiError:
      required:
      - status
      - message
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        message:
          type: string
